server:
  port: 8080
  display-name: api-gateway
#  context-path: /api-gateway

management:
  context-path: /api-gateway
  security:
    enabled: false

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.50.57:3306/whadmin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # druid配置
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    jdbcTypeForNull: NULL
    mapUnderscoreToCamelCase: true
zuul:
  ignored-services: '*'
  routes:
    config-server:  #config-center 为 serviceId
      path: /config-server/**
    paper:
      path: /paper/**

apigateway:
  customerTestStr: apigateway 属性更新...123456








