server:
  port: 8010
#  context-path: /paper

management:
  context-path: /paper
  security:
    enabled: false

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin

  sleuth:
    sampler:
      percentage: 1
#spring:
#  datasource:
#    name: test
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    # druid配置
#    druid:
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#
#mybatis:
#  mapperLocations: classpath:mybatis/mapper/*.xml
#  configuration:
#    cache-enabled: true
#    lazy-loading-enabled: true
#    jdbcTypeForNull: NULL
#    mapUnderscoreToCamelCase: true

paper:
  customerTestStr: paper 属性更新..111






